### ISSUE TITLE
提取后缺少SkeletonDataAssets

### ISSUE THREAD

**Issue by Haurilin** [ZeroFlyFly/WaifuSpineRuntime#3]
非常感谢大佬写的插件，在使用插件提取[克洛琳德H5](https://act.mihoyo.com/ys/event/e20240531clorinde-5k96dd/index.html)的时候发现spine缺少了SkeletonDataAssets，动画播放不了
![20240531132551](https://github.com/ZeroFlyFly/WaifuSpineRuntime/assets/80104498/5cf82973-e9a7-4f8a-8317-b8476ef570d5)
![20240531132601](https://github.com/ZeroFlyFly/WaifuSpineRuntime/assets/80104498/16b6fa00-5418-4e1a-9f19-5badee383c8d)
只有main_keluolinde_bird和main_keluolinde_bird_hou这两个文件夹下有SkeletonDataAssets，其余spine文件夹下没有。

**Comment by ZeroFlyFly** [comment]
你好，出现这个问题的原因是新版本的Spine中出现了spine version 为4.0-from-4.1-from-4.2.20 这样的版本格式，导致代码中阅读不正常，现在暂时添加代码特殊处理绕过，拉新版可以解决。后续会优化这部分的识别和修正，感谢提出的issue。

**Comment by Haurilin** [comment]
好的，感谢大佬回复👍🏻
