### ISSUE TITLE
is it support for new version web event preview?

### ISSUE THREAD

**Issue by sabrisangjaya** [ZeroFlyFly/WaifuSpineRuntime#8]
new version web preview right now is opened at https://genshin.hoyoverse.com/en/ , i only found vendor js from inspect element
https://act.hoyoverse.com/puzzle/hk4e/pz_QaiBDjkyxb/

![image](https://github.com/user-attachments/assets/5dc63234-f10f-437a-bcd7-ad45cec441b5)

**Comment by ZeroFlyFly** [comment]
Hi，sorry for the late reply~ I was busy with my work these days.

I have read through the js file you provided and it seems all the spine relate files are hardcoded in config.b4f66acd.js.

It should be 7 spine files in it.

You can get all files by searching  "atlas: " or  " json:" pattern.

I have no idea it would be new web style for genshine or not. So, supporting this website is still in consider.

This new website type is really different from the website I decoded before. Including this function might make the vendors decoder looks too complex.

However, if the later website are all in new type. I will support it as soon as possible.
